user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    upstream node_server {
        server 127.0.0.1:3000;
    }

    server {
        listen 80;
        server_name _;

        # Static HTML root
        root /usr/share/nginx/html;
        index index.html;

        # Serve static
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /stream {
            proxy_pass http://node_server/stream;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Super penting untuk SSE
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Connection '';
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            # Matikan gzip untuk SSE
            gzip off;
        }
    }
}
