[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true

[program:node]
command=node /app/server.js
autorestart=true
stdout_logfile=/var/log/node.log
stderr_logfile=/var/log/node.err
